### ISSUE TITLE
really interesting project but some basic how-to-use are needed

### ISSUE THREAD

**Issue by vesper8** [loonpwn/laradock-cli#1]
I just started using Laradock and am finding it quite bloated and it's been a chore trying to figure out how to trim all the fat so I can end up with configurations that are lean and viable on production

I was looking for possibly existing examples of such configs and came across your project.

It certainly looks promising! But I don't understand how to use it!

Are we supposed to clone this repo inside of an existing Laravel project? Or inside of a Laravel project already containing Laradock at its root?

I tried to create a "global" installation of your "laradock" but that didn't really work as intended.

When I try to run php laradock init inside a cloned folder it just complains about not finding any env variables

I also notice that your included docker-compose.yml has some opinions, for example it installs apache2 and not nginx.. is this meant to be just an example? and using your cli one is able to modify docker-compose's listed services through a cli interface?

I really want to use this! Just need a bit of guidance on how it's intended to be used across multiple Laravel projects without requiring to pull in lots of code into each.

Thanks for working on this! I think it's very needed

**Comment by harlan-zw** [comment]
Hi @vesper8 

Thanks for getting in touch! Let me preface my response that this project is actually a WIP and is not yet near a release. I apologise if the repo didn't convey that properly, will update it accordingly.

The intended usage of this will be adding it as dev dependency in composer, since it's not in packagist at the moment it's not really possible. You could try and clone the repo into your project and run `composer install` within it. I'm guessing the errors you got were around it not being able to read the `laradock/env-example` file.

I'll keep this ticket open for when I have a release ready version and let you know. I'll aim to have something ready by the end of the week, otherwise within the month

**Comment by vesper8** [comment]
you mean clone it as a subfolder inside an existing laravel project ?

I figured as much.. that it was a WIP.. but if it offers some functionality that's better than nothing.. I hope you will take the time to get it published on packagist and working as a dependency soon, even if the project isn't release-ready.. at least it will be easy to import and play with.. including forking and submitting PRs to. Right now it's just very hard to use it seems.. It's bad enough the way I'm currently using Laradock is a one-repo-per-project. I'm probably doing it wrong. But having a centralized installation of Laradock and only having a few configuration files committed/managed per project is where I want to be.. and I'm thinking this cli project of yours can get us there!

**Comment by harlan-zw** [comment]
Hi @vesper8 

Going to close this one since i've providing quite a bit more documentation and cleaned up a lot of the workflows.

Please open up a new issue if you have any specific issues. Keep in mind that you should refer to Laradock documentation for any docker related issues.

Thanks

**Comment by vesper8** [comment]
awesome! good job on getting the first official release out! I hope your project garners attention!

you can count on me on reporting issues and feedback as well as making feature requests

right off the bat I think it would be cool if you could save reusable default configurations, similar to what the vue-cli lets you do

it would also be cool to be able to edit a global configuration file, maybe something like ~/.laradock-cli.cfg 

where I could set things like a global include/exclude list, to filter out all the services I never want to install that are just bloating up the list
